### PR TITLE
fix int conversion

### PR DESCRIPTION
**Pull request by levkar**
fixes the integer conversion problem

### CODE REVIEW

**Comment by satterly** [comment]
What's the "integer conversion problem"? Can you paste an example error into the description?

**Comment by levkar** [comment]
Sorry for the bad description, I should have put it:

alerta.exceptions.ApiError: Error while running post-receive plugin 'alerta_forward': '〉=' not supported between instances of 'int' and 'str'

**Comment by satterly** [comment]
Have you tested this? I don't think `fw_count` is the problem here. I think it's the environment variable `FORWARD_MAX_LENGTH` that needs to be cast to an int.

**Comment by levkar** [comment]
It works after this change. You'd better test it as well.

**Comment by satterly** [comment]
please confirm how you are configuring this plugin. thanks.

**Comment by levkar** [comment]
we put below in environment part of the docker-compose file:

      - FORWARD_URL='http://172.16.16.60:8080/api'
      - FORWARD_API_KEY='1eEq8Fm0nTKyJACqXk-hFegWF42LV4TlXKgvKHk-'
      - FORWARD_MAX_LENGTH=3

it doesn't work without the patch. It works after the patch.

**Comment by levkar** [comment]
to test this we changed pip install part of docker-entrypoint.sh to my repo.

**Comment by levkar** [comment]
To be honest; loading additional modules from a predefined repo which is defined in docker-entrypoint.sh (and loading them on every time program starts) is a very bad idea. We are planning to build a new docker image for this.

**Pull request merged**
