### PR TITLE
add http proxy support for telegram plugin, add mattermost plugin

### PR DESCRIPTION
**Pull request by abenaguev**
this PR helps handle telegram proxy in alerta and telepot way (I hope..)
FYI:
https://github.com/nickoala/telepot/issues/309

### CODE REVIEW

**Comment by abenaguev** [comment]
I think, it's must be two PR. lacks of github knowledge :man_facepalming: 
So, @satterly , can you please check?

**Comment by satterly** [comment]
Yes, usually something like this would be two separate PR as they deal with different things. Howeber I'm happy to merge them as they are. Thanks a lot. :+1:

**Comment by abenaguev** [comment]
glad you'r finding this useful. and my profit is build custom image not needed anymore. now I have true CI/CD from upstream :smiling_imp: 

p.s. I forget to update plugins list on main page. can you please?

**Comment by satterly** [comment]
Done 👍

**Pull request merged**
