### PR TITLE
AMQP Plugin refactoring

### PR DESCRIPTION
**Pull request by JacksonHill**
Changed plugin name, and setup file to avoid collision with amqp package required by kombu.

### CODE REVIEW

**Comment by satterly** [comment]
Good work. This will become the standard template for all plugins. I'll work through them all and make sure they work in this new format. Thanks for your help in fixing this.

**Comment by satterly** [comment]
Reference http://helga.readthedocs.io/en/latest/plugins.html#plugins-packaging

**Comment by msupino** [comment]
had to add TOPIC in config

ERROR - Server plug-in 'amqp' could not be loaded: 'AMQP_TOPIC'
Server plug-in 'amqp' could not be loaded: 'AMQP_TOPIC'

default doesnt apply

**Comment by satterly** [comment]
@msupino you're right. There's a bug in the amqp plugin config. Fixing now.

**Comment by JacksonHill** [comment]
@msupino You cannot use amqp plugin without specifying a topic ;)

**Comment by satterly** [comment]
Ah. that is true. but it wasn't working as designed either. see #56

**Comment by JacksonHill** [comment]
Now i see.

**Pull request merged**
