### PR TITLE
Add SLACK_CHANNEL and ALERTA_UI_URL vars

### PR DESCRIPTION
**Pull request by minhdanh**
Make slack channel and alerta ui url configurable

### CODE REVIEW

**Comment by satterly** [comment]
Thanks! Can you bump the version number in `setup.py` to 0.1.3 ?

**Comment by minhdanh** [comment]
No problem. I've just made it.

**Comment by satterly** [comment]
Great. Thanks.

**Comment by minhdanh** [comment]
I deploy Alerta on heroku. So now how can I update package `alerta-slack` to the above commits?

**Comment by satterly** [comment]
I've just updated PyPI so yes, you can now redeploy Alerta to Heroku and it will pick up the new version.

**Comment by minhdanh** [comment]
Thank you.

**Comment by christianblunden** [comment]
@satterly Is this going to be merged? Slack plugin is currently broken due to missing ALERTA_UI_URL var

**Comment by satterly** [comment]
See #92

**Pull request merged**
