### PR TITLE
Show origin

### PR DESCRIPTION
**Pull request by freeseacher**
Include origin in slack notify message

### CODE REVIEW

**Comment by satterly** [comment]
I don't think origin should be labelled `Server` as it is meant to be the "name of monitoring component that generated the alert" (see http://docs.alerta.io/en/latest/api/alert.html#attributes) For example, "nagios-server-101" or "myInstrumentedApp" or "diskCheck.pl". It's meant to help you troubleshoot so that you know where an alert originated from and perhaps filter out alerts from that origin if you are getting flooded.

If you want to report what server an alert was for then you should be using `resource`. For example, `myHost10:/var/tmp` is a valid `resource`.

**Comment by freeseacher** [comment]
Ok, currently i am using supervisord eventlistener from contrib to send data about daemon restart and as far as i can see there are only one field contains server that event received from. 
That is origin. 
So probably we should change it there ?

**Comment by satterly** [comment]
Yes, this ...
```
resource=body['processname']
```
should probably be...
```
resource="%s: %s" % (headers['server'], body['processname'])
```
and `origin` should be `supervisord/evlistener.py`

**Comment by satterly** [comment]
Turns out `headers['server']` is not the server name so have to use `uname()` method to get it from the OS. See #39

**Pull request closed without merging**
