### PR TITLE
Slack dropping some messages from alerta due to >2s response

### PR DESCRIPTION
**Pull request by kwesterfeld2**
- The timeout on requests.post() was only 2 seconds, resulting in dropped messages to slack channel.
- Added better logging for slack API responses

### CODE REVIEW

**Comment by satterly** [comment]
Not sure just increasing the timeout to 30 seconds is the right approach. This would cause the HTTP response to hang for that length of time which I don't think is acceptable. 

Also, you don't mention why Slack is tacking >2 seconds to respond or how often.

Is there an alternative? Perhaps queueing failed notifications and retrying?

**Comment by kwesterfeld2** [comment]
Ah, I hadn't considered we are being called from synchronous code here, but I guess that makes sense.  Is there a queuing framework within alerta already to use?

I'm not sure how often it is happening, but our support folks started noticing that one integration we have (opsgenie) was receiving messages that are not showing up in slack.  The integration is coming from alerta and I can see that slack simply doesn't show some messages. 

I will check also rate-limiting responses.

Let's close this PR and I'll re-open once I know more or you can advise a better way to handle this.

**Comment by satterly** [comment]
The way the [mailer]() works is to read alerts off a message queue before sending emails. Slack could do the same and not ack the alert off the queue unless Slack has accepted the message. This is obviously more complex to develop, deploy and troubleshoot which makes me reluctant. Let me think about this some more. Closing for now as suggested.

**Comment by satterly** [comment]
I think the solution is to send post-receive hooks to be run by a celery queue and then the timeout can be longer and can retry if they fail. The foundations have been laid with this PR https://github.com/alerta/alerta/pull/693 so it should be possible without too much  additional development.

**Pull request closed without merging**
