### PR TITLE
added script to be run by consul alerts, pushing errors into altera api

### PR DESCRIPTION
**Pull request by msupino**

### CODE REVIEW

**Comment by msupino** [comment]
need these consul keys to work

consul-alerts/config/notifiers/custom/alerta:<path>/consul-alerta.py
alerta/apikey:'api-key' // alerta key for api access
alerta/apiurl:'api-url'  // alerta api url
alerta/timeout:5  // item timeout in alerta (default 86400)
alerta/max_retries:3 // max api attempts
alerta/sleep:2 // sleep between attemps
alerta/origin:consul // alert origin
alerta/alerttype:ConsulAlerts // alert type

**Comment by satterly** [comment]
Can you add a README that explains how to use this integration? A step by step guide like the one for [supervisor](https://github.com/alerta/alerta-contrib/tree/master/integrations/supervisor) is easy and would be very useful. Thanks.

**Comment by msupino** [comment]
added readme

**Comment by msupino** [comment]
Done.

**Comment by satterly** [comment]
Thanks.

**Pull request merged**
