### PR TITLE
Add Sentry version 9 webhook support

### PR DESCRIPTION
**Pull request by FloSew**
Add support for Sentry version 9 callbacks (alerta#281)

I had to also add my patch from #305 in order to have it working and tested correctly.

Here are some pictures of an alert sent from Sentry 9.1.2.

alerta_sentry_01
alerta_sentry_02

### CODE REVIEW

**Comment by FloSew** [comment]
@satterly could you have a look on this PR ?

**Comment by satterly** [comment]
If you rebase this PR I'll merge. Thanks! 👍

**Comment by satterly** [comment]
👍

**Comment by FloSew** [comment]
@satterly Thanks to you

**Pull request merged**
